[package]
name = "lockbox-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
lockbox = { path ="../lockbox" }
structopt = "*"
dirs = "*"
csv = "*"
serde = { version ="*", features = ["derive"] }

[[bin]]
name = "lockbox"
path = "src/bin.rs"
